### ISSUE TITLE
Handover to bincrafters

### ISSUE THREAD

**Issue by madebr** [sixten-hilborn/conan-libmikmod#1]
Hey,

I'm trying to package SDL2_mixer, which has a dependency on libmikmod for midi playback.

Do you consider handing over ownership of this conan package to bincrafters at https://github.com/bincrafters/community?

Thanks!

**Comment by madebr** [comment]
I see that you have created a repo with conan-sdl2_mixer.
Do you intend to hand this over to bincrafters? Or should someone else step in?

**Comment by sixten-hilborn** [comment]
Hi!

Sorry for the delayed answer. That's a great idea! I'll review this package and create a handover request to bincrafters.
I have to check that the [sdl2_mixer](https://github.com/sixten-hilborn/conan-sdl2_mixer) package and its dependencies are high-quality enough for a handover. Any feedback is of course welcome.

**Comment by madebr** [comment]
Let's do dependency per dependency.
You'll be the _master of ceremony_ :smiley:

**Comment by sixten-hilborn** [comment]
This recipe has been handed to bincrafters now: https://github.com/bincrafters/conan-libmikmod
I'll delete this repository soon as development will continue in the bincrafters repo, issues should be reported to bincrafters.
I've added an [issue in my sdl2_mixer repo](https://github.com/sixten-hilborn/conan-sdl2_mixer/issues/1) for handing over remaining packages related to sdl2_mixer.
